apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
   name: app-role
   namespace: default
rules:
   - apiGroups:
        - ""
        - apps
        - autoscaling
        - batch
        - extensions
        - policy
        - rbac.authorization.k8s.io
     resources:
        - pods
        - namespaces
        - nodes
     verbs: ["get", "list", "watch"] 
