apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
     name: app-rolebinding
     namespace: default
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: app-role
subjects:
   - namespace: default
     kind: ServiceAccount
     name: kubernetes-api


