apiVersion: v1
kind: Service
metadata:
   name: backend-kubernetes-services
   labels:
     name: backend-kubernetes-service
     app: kubernetes-app
spec:
   type: NodePort
   ports:
     - port: 80
       targetPort: 80
       nodePort: 30009
   selector:
       name: kubernetes-api-pod
       type: services
       tier: api
       app: kubernetes-app
