apiVersion: v1
kind: Secret
metadata:
   name: mysql-config
data:
   MYSQL_USER: ZGJ1c2Vy   
   MYSQL_HOST: ZGI=
   MYSQL_DATABASE: QWNjb3VudA==
   MYSQL_PASSWORD: ZGJ1c2VycGFzc3dvcmQ=
   MYSQL_RANDOM_ROOT_PASSWORD: MQ==
